# Simple workflow for deploying static content to GitHub Pages
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Next Tag
        run: |
          echo "${{ github.ref }}"
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/releases/next" ]]; then
            TAG="releases/next"  # Use the SHA of the push commit for main
          else
            TAG="${{ inputs.tag }}"  # Use the provided input tag for manual triggers
          fi
          echo "Tag: $TAG"
      # - name: Check folders
      #   run: |
      #     ls
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{inputs.tag}}
      #     path: server/renameme
      # - name: Check clone
      #   run: |
      #     cd ${{ github.workspace }}/server
      #     ls
      #     cd ${{ github.workspace }}/server/renameme
      #     ls
      # - name: Print Environment Variables
      #   run: |
      #     echo "GitHub Repository: $GITHUB_REPOSITORY"
      #     echo "GitHub Event Name: $GITHUB_EVENT_NAME"
      #     echo "GitHub Actor: $GITHUB_ACTOR"
      #     echo "GitHub Workflow: $GITHUB_WORKFLOW"
      #     # You can add more environment variables as needed

      # - name: Print Env Context
      #   run: |
      #     echo "Env Context:"
      #     echo "----------------"
      #     env

      # - name: Set Next Tag
      #   run: |
      #     if [ -n "${{ github.event.release.tag_name }}" ]
      #     then
      #       TAG="${{ github.event.release.tag_name }}"
      #     else
      #       TAG= "${{ inputs.tag }}"
      #     fi
      #     echo "Tag: $TAG"
