# Simple workflow for deploying static content to GitHub Pages
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["production"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Environment Variables
        run: |
          echo "GitHub Repository: $GITHUB_REPOSITORY"
          echo "GitHub Event Name: $GITHUB_EVENT_NAME"
          echo "GitHub Actor: $GITHUB_ACTOR"
          echo "GitHub Workflow: $GITHUB_WORKFLOW"
          # You can add more environment variables as needed

      - name: Print Env Context
        run: |
          echo "Env Context:"
          echo "----------------"
          env

      - name: Get Latest Release
        id: latest-release
        run: |
          # Use the GitHub API to get information about the latest release
          latest_release=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/username/repo/releases/latest")
          
          # Extract the version name from the JSON response
          version=$(echo "$latest_release" | jq -r '.tag_name')
          
          echo "Latest Version: $version"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
